config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'

  resources :artists do
    resources :songs
  end
  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :title, presence: true, uniqueness: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :find_artist, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    @artists = Artist.order(sort_column + " " + sort_direction)
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @artist.update_attributes(artist_params)
      redirect_to @artist
    else
      render 'edit'
    end
  end

  def destroy
    @artist.destroy

    redirect_to artists_path
  end

  private
  def find_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:user).permit(:name)
  end

  def sort_column
    params[:sort] || "name"
  end

  def sort_direction
    params[:direction] || "asc"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :find_song, only: [:destroy]
  before_action :set_artist

  def create
    @artist.songs.create!(song_params)
    redirect_to artist_path(@artist)
  end

  def destroy
    @song.destroy

    redirect_to artist_path(@artist)
  end

  private
  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def find_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title)
  end

  def sort_column
    params[:sort] || "name"
  end

  def sort_direction
    params[:direction] || "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||=column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<table>
  <tr>
    <th></th>
    <th><%= sortable "name", "Artist" %></th>
    <th><%= sortable "created_at", "Created at" %></th>
  </tr>
  <% @artists.each do |artist| %>
    <tr>
      <td><%= image_tag artist.photo, :class => "image"%></td>
      <td><%= link_to artist.name, artist %></td>
      <td><%= artist.created_at.strftime("%d/%m/%Y") %></td>
    </tr>
  <% end %>

</table>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= link_to "Delete Artist", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure?" } %>

<% @artist.songs.each do |song| %>
  <p><%= song.title %> - <%= link_to "Delete", artist_song_path(@artist, song), method: :delete, data: { confirm: "Are you sure?" } %></p>
<% end %>

<%= form_for [@artist, Song.new(artist: @artist)] do |f| %>
  <div class="form-group">
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.submit "Add Song" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/new.html.erb
<div class="form-wrapper">
<%= form_for @song do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.collection_select :artist_id, Artist.order(:name), :id, :name, include_blank: true %>
  </p>

  <p>
    <%= f.submit (@song.new_record? ? "Create" : "Edit"), class: "flex-right" %>
  </p>

  <p>
  </p>
<% end %>
</div>